# Generated by Django 5.2.5 on 2025-08-13 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('funcionando', 'Funcionando'), ('defeito', 'Com defeito'), ('quebrado', 'Quebrado'), ('roubado', 'Roubado'), ('manutencao', 'Em manutenção'), ('em estoque', 'Em estoque'), ('fora de estoque', 'Fora de estoque')], default='funcionando', help_text='Situação atual do equipamento', max_length=20),
        ),
    ]
