# Generated by Django 5.2.5 on 2025-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0002_alter_equipamento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='observacao',
            field=models.CharField(blank=True, null=True),
        ),
    ]
