# Generated by Django 5.2.5 on 2025-08-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0003_equipamento_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
