# Generated by Django 5.2.5 on 2025-08-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrimonio', '0004_alter_equipamento_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='numero_patrimonio',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
